### ISSUE TITLE
Issue with new node v.4.0.0

### ISSUE THREAD

**Issue by Apaksimen** [welearnjs/helpersApp#4]
sudo npm install nvm // install nvm
nvm download 0.12.7 // download node v0.12.7
nvm build 0.12.7
sudo nvm install 0.12.7
node -v // Check node version, now it's 0.12.7
npm install // No error

**Comment by benhalverson** [comment]
@Apaksimen what platform are you? Windows, Mac, Linux?
you shouldn't need to do sudo anything 
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.28.0/install.sh | bash installs node
nvm install v4.1.2 will install node
nvm alias default v4.1.2 will set your default.

**Comment by Apaksimen** [comment]
Thanks, this issue is already solved!
